---
title: "STAT 504-IC 1"
author: "Richel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
library(dplyr)
```

```{r 1.0}
head(gapminder)
```

```{r 2.0}
#QUESTION ONE

# Create the bar plot
ggplot(gapminder, aes(x = continent)) +
  geom_bar(fill = "orange") +
  xlab("Continent") +
  ylab("Count") +
  coord_flip() +
  theme_classic()

```

```{r 3.0}
#QUESTION 2
# Create the bar plot with stat_summary
ggplot(gapminder, aes(x = continent, y = gdpPercap)) +
  stat_summary(fun = median, geom = "bar", fill = "lightblue") +
  xlab("Continent") +
  ylab("Median of gdpPercap") +
  coord_flip() +
  theme_classic()

```

```{r 4.0}
#QUESTION 3
# Summarize data to calculate median GDP per capita for each continent
median_gdp_data <- gapminder %>%
  group_by(continent) %>%
  summarise(median_gdpPercap = median(gdpPercap))

# Create the bar plot using geom_bar
ggplot(median_gdp_data, aes(x = continent, y = median_gdpPercap)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  xlab("Continent") +
  ylab("Median of gdpPercap") +
  coord_flip() +
  theme_classic()

```